title: José Kabir Snell
logo: "/assets/pfp.jpg?raw=true"
description: >

  <p align="center">
  <a href="mailto:kabirsnell@gmail.com">Email</a> |
  <a href="https://www.linkedin.com/in/kabirsnell/">LinkedIn</a> |
  <a href="https://github.com/kabirjs">GitHub</a> 
  </p>

  Master of Data Science Student at UC Irvine, graduating December 2024. Passionate about all things data science and machine learning!
# show_downloads: true
theme: jekyll-theme-minimal
google_analytics: G-34GHE9PJDR
