title: José Kabir Snell
#logo:
description: Master of Data Science Student at UC Irvine, graduating December 2024. Graduated from the UC Santa Barbara in June 2023 with a B.S. in Statistics and Data Science. Passionate about data science and improving my machine learning skills!
# show_downloads: true
theme: jekyll-theme-minima
